missing data, invalid data, wrong domain (age = 170)

## Handling Missing Data with Pandas

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({
    'Column A': [1, np.nan, 30, np.nan],
    'Column B': [2, 8, 31, np.nan],
    'Column C': [np.nan, 9, 32, 100],
    'Column D': [5, 8, 34, 110],
})

In [3]:
df

   Column A  Column B  Column C  Column D
0       1.0       2.0       NaN         5
1       NaN       8.0       9.0         8
2      30.0      31.0      32.0        34
3       NaN       NaN     100.0       110

In [4]:
df.isnull()

   Column A  Column B  Column C  Column D
0     False     False      True     False
1      True     False     False     False
2     False     False     False     False
3      True      True     False     False

In [6]:
df.notnull()

   Column A  Column B  Column C  Column D
0      True      True     False      True
1     False      True      True      True
2      True      True      True      True
3     False     False      True      True

In [7]:
df.isnull().sum()

Column A    2
Column B    1
Column C    1
Column D    0
dtype: int64

In [8]:
df.dropna()

   Column A  Column B  Column C  Column D
2      30.0      31.0      32.0        34

In [9]:
df.dropna(axis=1)  # axis='columns' also works

   Column D
0         5
1         8
2        34
3       110

In [ ]:
df.dropna(thresh=3) # only drop it if there are 3 NaN

   Column A  Column B  Column C  Column D
0       1.0       2.0       NaN         5
1       NaN       8.0       9.0         8
2      30.0      31.0      32.0        34

In [ ]:
# Filling null values

# with an arbitrary value
s = ...
s.fillna(0)
s.fillna(s.mean())

In [ ]:
# Filling nulls with contiguous (close) values

s.fillna(method='ffill') # from front
s.fillna(method='bfill') # from behind

In [11]:
df.fillna(method='ffill', axis=0)

C:\Users\33034\AppData\Local\Temp\ipykernel_32200\3122255136.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', axis=0)

   Column A  Column B  Column C  Column D
0       1.0       2.0       NaN         5
1       1.0       8.0       9.0         8
2      30.0      31.0      32.0        34
3      30.0      31.0     100.0       110